-- ============================================================
-- Migration 005: Add product_line to mart.seasonal_components
-- Stage 3 Step A2 — NB product line seasonal decomposition
-- ============================================================

-- Add nullable product_line column
ALTER TABLE mart.seasonal_components
    ADD COLUMN IF NOT EXISTS product_line VARCHAR(50) DEFAULT NULL;

-- Drop old unique constraint (name auto-generated by PostgreSQL)
ALTER TABLE mart.seasonal_components
    DROP CONSTRAINT seasonal_components_brand_region_week_start_metric_name_dec_key;

-- New unique index with COALESCE for NULL-safe uniqueness
-- NULL product_line (brand-level) becomes '_brand' in index
CREATE UNIQUE INDEX IF NOT EXISTS uq_seasonal_components_full
    ON mart.seasonal_components (
        brand, region, week_start, metric_name,
        decomposition_method, COALESCE(product_line, '_brand')
    );
